name: pinecone
description: Unofficial Dart client for Pinecone vector database
version: 1.0.0
maintainer: Taza Technology LLC
repository: https://github.com/tazatechnology/pinecone
issue_tracker: https://github.com/tazatechnology/pinecone/issues
homepage: https://tazatechnology.com
documentation: https://github.com/tazatechnology/pinecone

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
