name: pinecone
description: Unofficial Dart client for Pinecone vector database
version: 0.1.0
maintainer: Taza Technology LLC
repository: https://github.com/tazatechnology/pinecone
issue_tracker: https://github.com/tazatechnology/pinecone/issues
homepage: https://tazatechnology.com
documentation: https://github.com/tazatechnology/pinecone

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.1.1
  json_annotation: ^4.8.0
  retrofit: ^4.0.1

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  swagger_parser: ^0.10.3
  retrofit_generator: ^6.0.0+3
