name: pineconedb
description: Unofficial Dart client for Pinecone vector database. For more details on Pinecone, please visit https://docs.pinecone.io/docs/overview.
version: 1.0.5
maintainer: Arcane Arts Inc.
repository: https://github.com/ArcaneArts/pineconedb
issue_tracker: https://github.com/ArcaneArts/pineconedb/issues
homepage: https://arcane.art
documentation: https://github.com/ArcaneArts/pineconedb
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  http: ">=1.0.0 <2.0.0"
  dart_mappable: ^4.4.0
dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.1.1
  test: ^1.25.15 
  dart_mappable_builder: ^4.4.0
scripts: 
  build: dart run build_runner build --delete-conflicting-outputs